name: 06 Action matrix

on:
  push:
    branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        
        strategy:
            matrix:
                node-version: [14, 16, 18]

        steps:
            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}

            - name: Check Node.js version
              run: node --version